#+begin_export latex
The program \texttt{coder} has hooks for imports, code tables, the
init function, and the main function.
#+end_export
#+begin_src go <<coder.go>>=
  package main
  import (
	  //<<Imports>>
  )

  //<<Variables>>

  func init() {
	  //<<Init function>>
  }

  func main() {
	  //<<Main function>>
  }
#+end_src
#+begin_export latex
\subsection{Coding rules}
We use the following table of non-degenerate codons, which is based on
the Bacterial, Archaeal and Plant Plastid Code
(\texttt{transl\_table=11})\footnote{\url{https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG11}}:

\begin{table}[h]
\centering
\begin{tabular}{c c}
\hline
Residue & Codon \\
\hline
\texttt{A} & \texttt{GCT} \\
\texttt{R} & \texttt{CGT} \\
\texttt{N} & \texttt{AAT} \\
\texttt{D} & \texttt{GAT} \\
\texttt{C} & \texttt{TGT} \\
\texttt{Q} & \texttt{CAA} \\
\texttt{E} & \texttt{GAA} \\
\texttt{G} & \texttt{GGT} \\
\texttt{H} & \texttt{CAT} \\
\texttt{I} & \texttt{ATT} \\
\texttt{L} & \texttt{CTG} \\
\texttt{K} & \texttt{AAA} \\
\texttt{M} & \texttt{ATG} \\
\texttt{F} & \texttt{TTT} \\
\texttt{P} & \texttt{CCT} \\
\texttt{S} & \texttt{TCT} \\
\texttt{T} & \texttt{ACT} \\
\texttt{W} & \texttt{TGG} \\
\texttt{Y} & \texttt{TAT} \\
\texttt{V} & \texttt{GTT} \\
\texttt{*} & \texttt{TAA} \\
\hline
\end{tabular}
\end{table}
To implement this table, we initialize three byte arrays:
\texttt{codons}, \texttt{nuclCodes}, and \texttt{residues}. These
arrays are to be filled with values.
#+end_export
#+begin_src go <<Variables>>=
  var codons [256][3]byte
  var nuclCodes [256]byte
  var residues [64]byte
#+end_src
#+begin_export latex
Inside the \texttt{init} function, we fill \texttt{codons},
\texttt{nuclCodes}, and \texttt{residues} with values.
#+end_export
#+begin_src go <<Init function>>=
  //<<Fill codons>>
  //<<Fill nucleotide codes>>
  //<<Fill residues>>
#+end_src
#+begin_export latex
\subsubsection{Codon lookup array (AA-to-DNA)}
The program \texttt{coder} uses the lookup array \texttt{codons} to
convert an amino acid residue to the corresponding DNA codon,
The \texttt{codons} array has the 20 amino acid residue bytes and an
asterisk as indexes, and arrays of DNA codons as values. Indexes other
than the meaningful 21 bytes are filled with triplets of unknown
nucleotides \texttt{N}.
#+end_export
#+begin_src go <<Fill codons>>=
  for i := range codons {
	  codons[i] = [3]byte{'N','N','N'}
  }

  codons['A'] = [3]byte{'G','C','T'}
  codons['R'] = [3]byte{'C','G','T'}
  codons['N'] = [3]byte{'A','A','T'}
  codons['D'] = [3]byte{'G','A','T'}
  codons['C'] = [3]byte{'T','G','T'}
  codons['Q'] = [3]byte{'C','A','A'}
  codons['E'] = [3]byte{'G','A','A'}
  codons['G'] = [3]byte{'G','G','T'}
  codons['H'] = [3]byte{'C','A','T'}
  codons['I'] = [3]byte{'A','T','T'}
  codons['L'] = [3]byte{'C','T','G'}
  codons['K'] = [3]byte{'A','A','A'}
  codons['M'] = [3]byte{'A','T','G'}
  codons['F'] = [3]byte{'T','T','T'}
  codons['P'] = [3]byte{'C','C','T'}
  codons['S'] = [3]byte{'T','C','T'}
  codons['T'] = [3]byte{'A','C','T'}
  codons['W'] = [3]byte{'T','G','G'}
  codons['Y'] = [3]byte{'T','A','T'}
  codons['V'] = [3]byte{'G','T','T'}
  codons['*'] = [3]byte{'T','A','A'}
#+end_src
#+begin_export latex
The array \texttt{residues} is used to convert a DNA codon to the
corresponding residue. A DNA codon cosists of 3 bytes, which are
\texttt{A}, \texttt{C}, \texttt{G}, or \texttt{T}. A 3-byte array
cannot be directly used as an index to the array of \texttt{residues},
so we will represent the codon triplets as integer indexes.

We first encode the nucleotides with 2-bit integers:
\begin{gather*}
A = 0_{10} = 00_2 \\
C = 1_{10} = 01_2 \\
G = 2_{10} = 10_2 \\
T = 3_{10} = 11_2
\end{gather*}

We fill the \texttt{nuclCodes} array with values:
\begin{gather*}
A = 0; C = 1; G = 2; T = 3 \\
\end{gather*}
Every other byte gets the invalid code \texttt{0xFF}.
#+end_export
#+begin_src go <<Fill nucleotide codes>>=
  for i := range nuclCodes {
	  nuclCodes[i] = 0xFF
  }

  nuclCodes['A'] = 0
  nuclCodes['C'] = 1
  nuclCodes['G'] = 2
  nuclCodes['T'] = 3
#+end_src
#+begin_export latex
\subsubsection{Amino acid residue lookup array (DNA-to-AA)}
The 64 possible DNA 3-mers can be represented with 6-bit integers
using bitwise \texttt{OR} and the nucleotide codes we have just
defined. For example, let's take the codon \texttt{GCT} for
alanine. In our encoding, it's \texttt{[$10_2$, $01_2$, $11_2$]}. To
convert this array into a 6-bit index, we use the formula:

\begin{gather*}
i = 10_2 \ll 4 \mathbin{|} 01_2 \ll 2 \mathbin{|} 11_2
\end{gather*}

We fill the \texttt{residues} array with 21 residues under indexes
that we calculate using the 2-bit nucleotide codes, which we look up
in the \texttt{nuclCodes} array using the codons we defined above. DNA
triplets not defined in \texttt{codons} will correspond to the
undefined residue '\texttt{X}'.
#+end_export
#+begin_src go <<Fill residues>>=
  for i := range residues {
	  residues[i] = 'X'
  }

  for _, r := range []byte("ARNDCQEGHILKMFPSTWYV*") {
	  c := codons[r]
	  c0 := nuclCodes[c[0]]
	  c1 := nuclCodes[c[1]]
	  c2 := nuclCodes[c[2]]
	
	  idx := (c0 << 4) | (c1 << 2) | c2
	  residues[idx] = r
  }
#+end_src
#+begin_export latex
\section{Main function and CLI}
In the main function, we declare the options, set the usage, set a
logger, parse the options and respond to them, read and process the
input, and report the results.
#+end_export
#+begin_src go <<Main function>>=
  //<<Declare options>>
  //<<Set usage>>
  //<<Set logger>>
  //<<Parse options>>
  //<<Respond to options>>
  //<<Read input>>
  //<<Process input>>
  //<<Report results>>
#+end_src
#+begin_export latex
The program \texttt{coder} has three options:

\begin{enumerate}
  \itemsep0em
  \item encode the input peptide sequences with non-degenerate codons;
  \item decode the input non-degenerate codons as a peptide sequences;
  \item print non-synonimous substitutions as dots instead of \texttt{X}.
\end{enumerate}

We declare those.
#+end_export
#+begin_src go <<Declare options>>=
  optE := flag.Bool("e", false, "encode peptides with DNA codons")
  optD := flag.Bool("d", false, "decode DNA codons as peptides")
  optX := flag.Bool("x", false, "print dot '.' instead of 'X'")
#+end_src
#+begin_export latex
We import \texttt{flag}.
#+end_export
#+begin_src go <<Imports>>=
  "flag"
#+end_src
#+begin_export latex
The usage consists of the actual usage message, an explanation of the
purpose of \texttt{coder}, and an example command.
#+end_export
#+begin_src go <<Set usage>>=
  u := "coder [option]..."
  p := "Encode or decode a biological sequence " +
	  "using a non-degenerate table of DNA codons."
  e := "coder -e peptide.faa\n         coder -d codons.fna"
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
We import \texttt{clio}.
#+end_export
#+begin_src go <<Imports>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
We set the standard logger \texttt{log} to print the program's name in
message prefixes.
#+end_export
#+begin_src go <<Set logger>>=
  log.SetPrefix("coder: ")
  log.SetFlags(log.Lmsgprefix)
#+end_src
#+begin_export latex
We import \texttt{log}.
#+end_export
#+begin_src go <<Imports>>=
  "log"
#+end_src
#+begin_export latex
We parse the options and non-flag arguments.
#+end_export
#+begin_src go <<Parse options>>=
  flag.Parse()
  args := flag.Args()
#+end_src
#+begin_export latex
We respond to the usage of \texttt{-d} and \texttt{-e}: if neither or
both are used, we ask the user to choose one and exit. We also check
if exactly one non-flag argument is specified. This argument is
expected to be the input file name.
#+end_export
#+begin_src go <<Respond to options>>=
  edBoth := *optE && *optD
  edNone := *optE == false && *optD == false
  if edNone || edBoth {
	  log.Fatal("please use either encode or decode mode")
  }

  if len(args) != 1 {
	  log.Fatal("please specify the input file")
  }
#+end_src
#+begin_export latex
The first non-flag argument is the path to the input file. We try to
open the file and treat any error as fatal. If there were no errors,
we read all \texttt{fasta} entries from the input file.
#+end_export
#+begin_src go <<Read input>>=
  path := args[0]
  file, err := os.Open(path)
  if err != nil {
	  log.Fatal("couldn't open file %v: %v", path, err)
  }
  sequences := fastautils.ReadAll(file)
#+end_src
#+begin_export latex
We read \texttt{os}, \texttt{fasta}, and \texttt{fastautils}.
#+end_export
#+begin_src go <<Imports>>=
  "os"
  "github.com/evolbioinf/fasta"
  "github.com/ivantsers/fastautils"
#+end_src
#+begin_export latex
We initialize the slice of result sequences and process the
input. There are two ways to deal with the input: either encode amino
acid residues, or decode DNA codons, whichever the user has chosen.
#+end_export
#+begin_src go <<Process input>>=
  var result []*fasta.Sequence

  if *optE {
	  //<<Encode residues>>
  }

  if *optD {
	  //<<Decode codons>>
  }
#+end_src
#+begin_export latex
\subsubsection{Encode amino acid residues}
We encode each input peptide sequence with codons. For this, we get
the original header and data, the we initialize a slice with a tripled
capacity of the original data. We also initialize a counter
\texttt{j}, which tracks the current position in the growing
slice. Then for each byte of the original data we add nucleotides of
the corresponding codons to the slice we have just initialized. Once
we are done, we create a new \texttt{fasta} sequence and append it to
the result.
#+end_export
#+begin_src go <<Encode residues>>=
  for _, seq := range sequences {
	  h := seq.Header()
	  d := seq.Data()
	  encodedData := make([]byte, 3 * len(d))
	  j := 0
	  for _, r := range d {
		  //<<Add nucleotides to the encoded data>>
	  }
	  encodedSeq := fasta.NewSequence(h, encodedData)
	  result = append(result, encodedSeq)
  }
#+end_src
#+begin_export latex
We get get a residue's codon from the lookup table and insert the
nucleotides one by one into the encoded data. After that, we add three
to the position tracker \texttt{j}.
#+end_export
#+begin_src go <<Add nucleotides to the encoded data>>=
  c := codons[r]
  encodedData[j] = c[0]
  encodedData[j+1] = c[1]
  encodedData[j+2] = c[2]
  j += 3
#+end_src
#+begin_export latex
\subsubsection{Decode DNA codons}
We decode each triplet of the input nucleotide sequence as amino acid
residues. For this, we get the original header and data, then we try
to decode the sequence using three reading frames (+0, +1, +2
nucleotides). After the decoding, we create a new \texttt{fasta}
sequence that using the best reading frame data and append it to the
result.
#+end_export
#+begin_src go <<Decode codons>>=
  for _, seq := range sequences {
	  h := seq.Header()
	  d := seq.Data()
	  lenD := len(d)
	  bestFrameScore := 0
	  bestFrameData := make([]byte, lenD / 3)
	  bestFrameName := 0
	  for f := 0; f < 3; f++ {
		  //<<Decode a reading frame>>
	  }
	  newH := fmt.Sprintf("%s frame=%d", h, bestFrameName)
	  decodedSeq := fasta.NewSequence(newH, bestFrameData)
	  result = append(result, decodedSeq)
  }
#+end_src
#+begin_export latex
we initialize a slice for decoded data with a one-third capacity of
the original data. We also initialize a counter \texttt{j}, which
tracks the current position in the growing slice. We also initialize
the frame's score. Then for each three bytes of the original data we
add amino acid residues to the decoded data. After that we score the
current reading frame and update the best score and data.
#+end_export
#+begin_src go <<Decode a reading frame>>=
  frameLen := (lenD - f) / 3
  frameData := make([]byte, frameLen)
  j := 0
  frameScore := 0
  for i := f; i + 2 < lenD; i += 3 {
	  //<<Add amino acid residues to the encoded data>>
  }
  //<<Score the reading frame>>
  //<<Update the best frame score and data>>
#+end_src
#+begin_export latex
We convert the current codon's nucleotides to 2-bit codes and validate
the codes. After that, we calculate a 6-bit index for the current
codon and use it to get corresponding residues from the lookup
array. We append the residue to the decoded data and increase the
current position counter.
#+end_export
#+begin_src go <<Add amino acid residues to the encoded data>>=
  c0 := nuclCodes[d[i]]
  c1 := nuclCodes[d[i + 1]]
  c2 := nuclCodes[d[i + 2]]
  //<<Validate nucleotide codes>>
  idx := (c0 << 4) | (c1 << 2) | c2
  frameData[j] = residues[idx]
  j++
#+end_src
#+begin_export latex
We append the undefined residue '\texttt{X}' to the data if any of the
nucleotide codes in the triplet is invalid.
#+end_export
#+begin_src go <<Validate nucleotide codes>>=
  if c0 == 0xFF || c1 == 0xFF || c2 == 0xFF {
	  frameData[j] = 'X'
	  j++
	  continue
  }
#+end_src
#+begin_export latex
The score of the reading frame is the number of defined residues, that
is, not the undefined nucleotide \texttt{'X'} or translation
termination '\texttt{*}'
#+end_export
#+begin_src go <<Score the reading frame>>=
  for _, r := range frameData {
	  if r != 'X' && r != '*' {
		  frameScore++
	  }
  }
#+end_src
#+begin_export latex
We update the best score and the best frame data if the current frame
score is greater than the current best score.
#+end_export
#+begin_src go <<Update the best frame score and data>>=
  if frameScore > bestFrameScore {
	  bestFrameScore = frameScore
	  bestFrameData = frameData
	  bestFrameName = f
  }
#+end_src
#+begin_export latex
We replace '\texttt{X}' with dot if the user has opted for it. Then we
print the result sequence to the \texttt{stdout}.
#+end_export
#+begin_src go <<Report results>>=
  if *optX {
	    //<<Replace Xs with dots>>
  }

  for _, res := range result {
	  fmt.Println(res)
  }
#+end_src
#+begin_export latex
We import \texttt{fmt}.
#+end_export
#+begin_src go <<Imports>>=
  "fmt"
#+end_src
#+begin_export latex
We iterate over the ouput sequences and subsitute \texttt{'X'} with
\texttt{'.'}.
#+end_export
#+begin_src go <<Replace Xs with dots>>=
  for _, res := range result {
	  data := res.Data()
	  for i, b := range data {
		  if b == 'X' {
			  data[i] = '.'
		  }
	  }
  }
#+end_src
